services:
  etl_pipeline:
    image: etl_pipeline
    container_name: etl_pipeline
    build: 
      context: ./
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    # env_file: 
    #   - .env
    environment:
      MOTHERDUCK_TOKEN: ${MOTHERDUCK_TOKEN}
      API_KEY: ${API_KEY}
      DATABASE_NAME: ${DATABASE_NAME}
    command: tail -f /dev/null  # This keeps the container running
